# Set tmux to use zsh
set -g default-shell /bin/fish

###
# BINDS ------------------------------------------------------
###
# Reload config file (change file location to your the tmux.conf you want to use)
unbind r
bind r source-file ~/.tmux.conf

# Remap prefix from to 'C-a'
unbind C-b
set -g prefix C-space
bind-key C-space send-prefix # Allows C-a C-a to send C-a to applications

# Set new window and pane to have the same path 
unbind '"'
unbind %
bind c new-window -c "#{pane_current_path}"
bind h split-window -c "#{pane_current_path}"
bind v split-window -h -c "#{pane_current_path}"

###
# OPTIONS -------------------------------------------------------
###
# Fix the numbering
set -g base-index 1
set -g pane-base-index 1

set -g mouse on
set -g set-titles on
set -g set-titles-string "#{pane_title}"
set -s focus-events on
set -s extended-keys on
set -s escape-time 0

# set -g terminal-features "xterm-kitty:RGB,paste"
set -g default-terminal "xterm-kitty"

###
#STYLE -----------------------------------------------------------
###
# Position + layout
set -g status-position top
set -g status-justify centre
set -g status-left "#S "
set -g status-right "#(whoami)@#H"
set-window-option -g window-status-current-format " #I:#W"
set-window-option -g window-status-format " #I:#W"



###
#PLUGIN ----------------------------------------------------------
###
# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'seebi/tmux-colors-solarized'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'christoomey/vim-tmux-navigator'

# Tmux-resurrect 
set -g @resurrect-save 'C-s'
set -g @resurrect-restore 'C-r'
# set -g @resurrect-strategy-nvim 'session'
set -g @resurrect-capture-pane-contents 'on'

# vim-tmux-navigator
set -g @vim_navigator_mapping_left "C-Left C-h"  # use C-h and C-Left
set -g @vim_navigator_mapping_right "C-Right C-l"
set -g @vim_navigator_mapping_up "C-Up C-k"
set -g @vim_navigator_mapping_down "C-Down C-j"
set -g @vim_navigator_mapping_prev ""  # removes the C-\ binding

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'
