# reload config file (change file location to your the tmux.conf you want to use)
unbind r
bind r source-file ~/.tmux.conf

# remap prefix from to 'C-a'
unbind C-b
set -g prefix C-a


# split panes using | and -
bind \\ split-window -h
bind - split-window -v
unbind '"'
unbind %

# vim keys to select pane
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

# fix the numbering
set -g base-index 1
set -g pane-base-index 1

# enable mouse support
set -g mouse on

set -g set-titles on
set -g set-titles-string "#{pane_title}"

# set new window and pane to have the same path 
bind c new-window -c "#{pane_current_path}"
bind - split-window -c "#{pane_current_path}"
bind \\ split-window -h -c "#{pane_current_path}"

set -s focus-events on
set -s extended-keys on

set -s escape-time 0

# set tmux to use zsh
set -g default-shell /bin/zsh

###
#STYLE
###

set -g status-position top

set -g status-left "#S "
set -g status-justify centre 
set -g status-right "#(whoami)@#H"


# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'seebi/tmux-colors-solarized'


# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm
