wallpaper {
    monitor = eDP-1
    path = ~/Pictures/Wallpaper/kimminhee.webp
    fit_mode = cover
}

wallpaper {
    monitor = HDMI-A-1
    path = ~/Pictures/Wallpaper/kimminhee.webp
    fit_mode = cover
}

wallpaper {
    monitor = 
    path = ~/Pictures/Wallpaper/mainaito1.jpeg
    fit_mode = cover
}

ipc = true
splash = false
