# Set tmux to use zsh
set -g default-shell /bin/fish

###
# BINDS ------------------------------------------------------
###

unbind C-b
set -g prefix M-space
bind-key M-space send-prefix

# Set new window and pane to have the same path 
unbind '"'
unbind %

bind c new-window -c "#{pane_current_path}"
bind h split-window -c "#{pane_current_path}"
bind v split-window -h -c "#{pane_current_path}"
bind x kill-pane
bind X kill-window

bind -n M-1 if-shell "tmux select-window -t :1" "" "new-window -c '#{pane_current_path}' -t :1"
bind -n M-2 if-shell "tmux select-window -t :2" "" "new-window -c '#{pane_current_path}' -t :2"
bind -n M-3 if-shell "tmux select-window -t :3" "" "new-window -c '#{pane_current_path}' -t :3"
bind -n M-4 if-shell "tmux select-window -t :4" "" "new-window -c '#{pane_current_path}' -t :4"
bind -n M-5 if-shell "tmux select-window -t :5" "" "new-window -c '#{pane_current_path}' -t :5"
bind -n M-6 if-shell "tmux select-window -t :6" "" "new-window -c '#{pane_current_path}' -t :6"
bind -n M-7 if-shell "tmux select-window -t :7" "" "new-window -c '#{pane_current_path}' -t :7"

bind C command-prompt -p "new session name:" "new-session -d -s '%%' ; switch-client -t '%%'"
bind G command-prompt -p "run command in background session:" 'run-shell "
  target=69;
  while tmux has-session -t \"\$target\" 2>/dev/null; do
    target=\$((target + 1));
  done;
  dir=\"\$(tmux display-message -p \"#{pane_current_path}\")\";
  tmux new-session -d -s \"\$target\" -c \"\$dir\" %1
"'

###
# OPTIONS -------------------------------------------------------
###
# Fix the numbering
set -g base-index 1
set -g pane-base-index 1

set -g mouse on
set -g set-titles on
set -g set-titles-string "#{pane_title}"
set -s focus-events on
set -s extended-keys on
set -s escape-time 0
set -g default-terminal "tmux-256color"

###
#STYLE -----------------------------------------------------------
###
# Position + layout

set -g status-position top
set -g status-justify centre

# Theme forestbones
set -g status-left ' #[fg=#A9C181,bold]#{s/root//:client_key_table}'
set -g status-right '#[fg=#D69AB7,bold][#S] #[nobold]#(whoami)@#H '
set -g status-style "fg=#D69AB7,bg=#3E4850"

set -g window-status-current-format "#[fg=#D69AB7,bold][#I:#W]"
set -g window-status-format "#I:#W"

set -g pane-border-style "fg=#D69AB7"
set -g pane-active-border-style "fg=#D69AB7"

set -g message-style "fg=#A9C181,bg=#3E4850,bold,fill=#3E4850"
set -g message-command-style "fg=#A9C181,bg=#3E4850,bold,fill=#3E4850"

set -g display-panes-active-colour '#D69AB7'
set -g display-panes-colour '#D69AB7'

set -g clock-mode-colour '#D69AB7'
set -g mode-style "fg=#2C343A,bg=#615B51"


###
#PLUGIN ----------------------------------------------------------
###
# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'christoomey/vim-tmux-navigator'
set -g @plugin 'ThePrimeagen/tmux-sessionizer'
set -g @plugin 'tmux-plugins/tmux-copycat'

# tmux-sessionizer
bind -r f run-shell "tmux neww ~/.tmux/plugins/tmux-sessionizer/tmux-sessionizer"

# Tmux-resurrect 
set -g @resurrect-save 'C-s'
set -g @resurrect-restore 'C-r'
set -g @resurrect-capture-pane-contents 'on'

# vim-tmux-navigator
set -g @vim_navigator_mapping_left "C-Left C-h"
set -g @vim_navigator_mapping_right "C-Right C-l"
set -g @vim_navigator_mapping_up "C-Up C-k"
set -g @vim_navigator_mapping_down "C-Down C-j"
set -g @vim_navigator_mapping_prev ""  # removes the C-\ binding

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'
