# Set tmux to use zsh
set -g default-shell /bin/fish

###
# BINDS ------------------------------------------------------
###

unbind C-b
set -g prefix C-space
bind-key C-space send-prefix

# Set new window and pane to have the same path 
unbind '"'
unbind %
bind c new-window -c "#{pane_current_path}"
bind h split-window -c "#{pane_current_path}"
bind v split-window -h -c "#{pane_current_path}"

# unbind '['
# unbind '('
# unbind '@'
# unbind '^'
# unbind '{'
# unbind 1
# unbind 2
# unbind 3
# unbind 4
# unbind 5
# bind '@' select-window -t 1
# bind '[' select-window -t 2
# bind '{' select-window -t 3
# bind '(' select-window -t 4
# bind '^' select-window -t 5

###
# OPTIONS -------------------------------------------------------
###
# Fix the numbering
set -g base-index 1
set -g pane-base-index 1

set -g mouse on
set -g set-titles on
set -g set-titles-string "#{pane_title}"
set -s focus-events on
set -s extended-keys on
set -s escape-time 0
set -g default-terminal "xterm-kitty"

###
#STYLE -----------------------------------------------------------
###
# Position + layout
set -g status-position top
set -g status-justify centre
set -g status-left "#S "
set -g status-right "#(whoami)@#H"
set-window-option -g window-status-current-format " #I:#W"
set-window-option -g window-status-format " #I:#W"



###
#PLUGIN ----------------------------------------------------------
###
# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'seebi/tmux-colors-solarized'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'christoomey/vim-tmux-navigator'
set -g @plugin 'ThePrimeagen/tmux-sessionizer'

# tmux-sessionizer
bind -r f run-shell "tmux neww ~/.tmux/plugins/tmux-sessionizer/tmux-sessionizer"
# bind -r 1 run-shell "tmux neww ~/.tmux/plugins/tmux-sessionizer/tmux-sessionizer -s 0"
# bind -r 2 run-shell "tmux neww ~/.tmux/plugins/tmux-sessionizer/tmux-sessionizer -s 1"
# bind -r 3 run-shell "tmux neww ~/.tmux/plugins/tmux-sessionizer/tmux-sessionizer -s 2"
# bind -r 4 run-shell "tmux neww ~/.tmux/plugins/tmux-sessionizer/tmux-sessionizer -s 3"

# Tmux-resurrect 
set -g @resurrect-save 'C-s'
set -g @resurrect-restore 'C-r'
set -g @resurrect-capture-pane-contents 'on'

# vim-tmux-navigator
set -g @vim_navigator_mapping_left "C-Left C-h"  # use C-h and C-Left
set -g @vim_navigator_mapping_right "C-Right C-l"
set -g @vim_navigator_mapping_up "C-Up C-k"
set -g @vim_navigator_mapping_down "C-Down C-j"
set -g @vim_navigator_mapping_prev ""  # removes the C-\ binding

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'
